export type AgentKind = "codex" | "claude-code" | "opencode" | "pi" | "generic";
export type WikiLinkStyle = "wikilinks" | "markdown";
export type PageNamingStyle = "title-case" | "sentence-case" | "kebab-case";

export const SCHEMA_VERSION = 2;
export const MANAGED_START = "<!-- second-brain:schema:start -->";
export const MANAGED_END = "<!-- second-brain:schema:end -->";
export const CUSTOM_START = "<!-- second-brain:custom:start -->";
export const CUSTOM_END = "<!-- second-brain:custom:end -->";

export interface AgentSchemaTemplateOptions {
  agent: AgentKind;
  customCategories: string[];
  domain: string;
  frontmatter: boolean;
  pageNaming: PageNamingStyle;
  projectName: string;
  sourceHandling: string;
  styleGuide: string;
  wikiLinkStyle: WikiLinkStyle;
}

export function getSchemaFilename(agent: AgentKind): string {
  switch (agent) {
    case "claude-code":
      return "CLAUDE.md";
    case "pi":
      return "PI.md";
    case "opencode":
      return "OPENCODE.md";
    case "codex":
    case "generic":
      return "AGENTS.md";
  }
}

export function getAgentDisplayName(agent: AgentKind): string {
  switch (agent) {
    case "codex":
      return "Codex";
    case "claude-code":
      return "Claude Code";
    case "opencode":
      return "OpenCode";
    case "pi":
      return "Pi";
    case "generic":
      return "a generic coding agent";
  }
}

export function renderAgentSchemaTemplate(options: AgentSchemaTemplateOptions): string {
  const fileName = getSchemaFilename(options.agent);
  const agentName = getAgentDisplayName(options.agent);
  const managedLines = renderManagedSection(options, agentName);

  return [
    `# ${fileName}`,
    "",
    "Generated by `second-brain schema`. Re-run the CLI or `second-brain upgrade` to refresh the managed instructions.",
    "",
    MANAGED_START,
    ...managedLines,
    MANAGED_END,
    "",
    CUSTOM_START,
    "## Project Customizations",
    "",
    "Add project-specific instructions here. `second-brain upgrade` preserves this block when possible.",
    CUSTOM_END,
    ""
  ].join("\n");
}

function renderManagedSection(
  options: AgentSchemaTemplateOptions,
  agentName: string
): string[] {
  const wikiLinkRule =
    options.wikiLinkStyle === "wikilinks"
      ? "Use wiki links like `[[Page Name]]` for internal references. Use aliases as `[[Page Name|Label]]` only when the label improves readability."
      : "Use standard markdown links for internal references, with repository-relative paths that remain stable after moves.";

  const frontmatterRules = options.frontmatter
    ? [
        "Every maintained wiki page should begin with YAML frontmatter using this shape:",
        "",
        "```yaml",
        "---",
        "title: Page Title",
        "type: entity|concept|topic|source-note|index",
        "status: active",
        "updated: YYYY-MM-DD",
        "aliases: []",
        "tags: []",
        "sources: []",
        "---",
        "```"
      ]
    : ["Do not add YAML frontmatter unless the user explicitly introduces it later."];

  const categories = ["entities", "concepts", "topics", ...options.customCategories];

  return [
    `schema-version: ${SCHEMA_VERSION}`,
    `target-agent: ${options.agent}`,
    "",
    "## Core Contract",
    "",
    `You are ${agentName} operating inside "${options.projectName}".`,
    "This CLI is only the setup and configuration layer. It does not ingest, query, lint, doctor, or fix the wiki itself.",
    "You do the actual wiki work: reading sources, extracting knowledge, updating pages, answering questions, and repairing structure.",
    "Treat this file as the operational contract for how the repository should be maintained.",
    "",
    "## Repository Model",
    "",
    "- `sources/` contains raw user-owned inputs. Do not overwrite them during normal maintenance.",
    "- `sources/inbox/` holds newly added material waiting for ingest.",
    "- `sources/archive/` holds processed material when the workflow chooses to archive it.",
    "- `wiki/` is the durable markdown knowledge layer that should improve over time.",
    "- `wiki/index.md` is the top-level navigation page and should reflect the actual wiki structure.",
    "- `wiki/log.md` is append-only and records meaningful maintenance events.",
    "- `schema/` is optional support material for these instructions.",
    "",
    "## Domain And Style",
    "",
    `Primary domain/topic: ${options.domain}`,
    "",
    `Preferred style conventions: ${options.styleGuide}`,
    "",
    "## Default Wiki Conventions",
    "",
    wikiLinkRule,
    `Page naming style: \`${options.pageNaming}\`. Use stable, predictable names and avoid near-duplicates.`,
    ...frontmatterRules,
    "",
    "Default wiki page categories:",
    ...categories.map((category) => `- \`${category}\``),
    "",
    "## Global Rules",
    "",
    "1. Prefer updating an existing page over creating a duplicate page with overlapping scope.",
    "2. Preserve a distinction between sourced facts, synthesis, speculation, and open questions.",
    "3. Keep claims grounded in specific source material whenever possible.",
    "4. When you create, rename, or remove a page, update `wiki/index.md` in the same pass.",
    "5. Append a dated note to `wiki/log.md` for meaningful wiki changes.",
    "6. If uncertainty exists, represent it explicitly instead of smoothing it away.",
    "7. Keep markdown portable. Avoid agent-specific syntax inside wiki pages.",
    "8. Prefer incremental maintenance over large speculative restructures unless the user asks for one.",
    "",
    "## Ingest Workflow",
    "",
    "When the user asks you to ingest new sources, follow this sequence:",
    "",
    "1. Read the source files in `sources/inbox/` or the user-specified path set.",
    "2. Identify the document type, scope, date, authorship, and why it matters to this repository.",
    "3. Produce a concise source summary in the relevant wiki page or note, preserving important nuance.",
    "4. Extract named entities, concepts, topics, events, decisions, metrics, and unresolved questions.",
    "5. Update existing pages first. Create new pages only when the subject is important enough to deserve durable reuse.",
    "6. Add cross-links between related pages so the graph remains traversable.",
    "7. Update `wiki/index.md` so the new or newly relevant material is discoverable.",
    "8. Append a dated entry to `wiki/log.md` describing the ingest pass.",
    `9. Source handling preference: ${options.sourceHandling}`,
    "",
    "## Query Workflow",
    "",
    "When the user asks a question about repository knowledge:",
    "",
    "1. Start from `wiki/index.md`, relevant topic pages, and the most connected supporting pages.",
    "2. Read only the pages needed to answer accurately; expand outward through links when coverage is thin.",
    "3. Synthesize from the maintained wiki rather than re-deriving everything from raw sources unless necessary.",
    "4. If the wiki is missing a needed concept, say what is missing and which source or page should be updated.",
    "5. If the answer creates durable knowledge, file it back into the relevant wiki page or create a clearly scoped page for it.",
    "",
    "## Lint And Doctor Workflow",
    "",
    "When the user asks you to audit, lint, doctor, or clean the wiki, check for at least the following:",
    "",
    "1. Orphan pages with no meaningful inbound or outbound links.",
    "2. Broken internal links, redirects that should be normalized, and title mismatches.",
    "3. Duplicate or overlapping pages that should be merged or clarified.",
    "4. Stale summaries, outdated statuses, and pages that drift from recent sources.",
    "5. Missing cross-references between strongly related pages.",
    "6. Contradictions between pages or within a page.",
    "7. Unsupported claims that should cite or point to a source-derived page.",
    "8. Placeholder text, TODOs, empty sections, and formatting drift.",
    "9. Index entries that point to removed content or fail to point to important active content.",
    "",
    "## Fix Workflow",
    "",
    "When the user asks you to fix issues in the wiki:",
    "",
    "1. Repair broken links and normalize them to the project link convention.",
    "2. Create short stub pages for important broken references when the target clearly should exist.",
    "3. Merge duplicate pages when one canonical page is obvious, then update inbound references.",
    "4. Normalize headings, section order, and formatting where drift hurts maintainability.",
    "5. Refresh `wiki/index.md` and `wiki/log.md` after the repair pass.",
    "",
    "## Page Shape",
    "",
    "Use a simple, durable structure unless a page needs something more specific:",
    "",
    "1. Title",
    "2. Short summary",
    "3. Key facts or notes",
    "4. Relationships / linked pages",
    "5. Sources or evidence trail",
    "6. Open questions or gaps",
    "",
    "## Naming Guidance",
    "",
    "- Entities: singular proper names like `Ada Lovelace`, `OpenAI`, `SQLite`.",
    "- Concepts: durable abstractions like `Retrieval Augmented Generation` or `Decision Journaling`.",
    "- Topics: broader synthesis pages like `AI Agent Tooling Landscape`.",
    "- Prefer one canonical page title and link aliases through redirects or explicit mentions rather than fragmented duplicates.",
    "",
    "## Agent-Specific Conventions",
    "",
    ...renderAgentConventions(options.agent)
  ];
}

function renderAgentConventions(agent: AgentKind): string[] {
  switch (agent) {
    case "codex":
      return [
        "- Respect repository instructions as the primary contract and keep edits tight and reviewable.",
        "- Update the wiki directly instead of leaving durable answers only in terminal output.",
        "- Prefer command-line inspection and precise file edits over broad rewrites."
      ];
    case "claude-code":
      return [
        "- This repository uses `CLAUDE.md` as the primary instruction file for Claude Code.",
        "- For larger ingest or cleanup passes, sketch a short execution plan and then perform the edits directly.",
        "- Keep the final terminal summary brief and push durable detail into markdown files."
      ];
    case "opencode":
      return [
        "- This repository uses `OPENCODE.md` as the primary instruction file for OpenCode-style agents.",
        "- Keep markdown highly portable and avoid conventions that only one coding agent understands.",
        "- Normalize links, names, and section shapes so automation stays predictable."
      ];
    case "pi":
      return [
        "- This repository uses `PI.md` as the primary instruction file for Pi-style agents.",
        "- Default to concise edits, explicit uncertainty, and strong traceability back to source material.",
        "- Repair and consolidate before expanding the page graph."
      ];
    case "generic":
      return [
        "- This file is meant to work for any coding agent, so keep workflows explicit and tooling assumptions minimal.",
        "- Favor plain markdown and stable repository conventions over assistant-specific features.",
        "- Optimize for future maintainability rather than short-term convenience."
      ];
  }
}
